### ISSUE TITLE
LDAP Configuration help

### ISSUE THREAD

**Issue by kopax** [kwk/docker-registry-setup#19]
Hi @kwk , thanks for sharing this!

I have a production docker registry v2 server where I use htaccess authentication behind nginx https reverse and public proxy. 

I want to replace htpasswd authentication with ldap authentication. We use docker registry image.

I don't see any Dockerfile on your repo nor any client installation for ldap on the registry server.

How did you manage to configure it? Is there any tutorial you have followed?

Thanks and best

**Comment by kwk** [comment]
Hi @kopax,

you can see [here](https://github.com/kwk/docker-registry-setup#how-to-run) that I run `docker-compose`. That picks up the [`docker-compose.yaml`](https://github.com/kwk/docker-registry-setup/blob/101aa6e8cba1c58174cceee549383efcdfb0fb15/docker-compose.yml#L25) file. That in turn starts an LDAP server which is configured with this [`Dockerfile`](https://github.com/kwk/docker-registry-setup/blob/101aa6e8cba1c58174cceee549383efcdfb0fb15/ldap/Dockerfile). This should give you a basic understanding of how I setup the LDAP for this demonstration.

Let me know if you have more questions and feel free to re-open this issue if needed.
