### ISSUE TITLE
Do not log plain text password when binding

### ISSUE THREAD

**Issue by SydOps** [kwk/docker-registry-setup#5]
With the commit in 

https://github.com/cesanta/docker_auth/commit/5ea722c9dc303e0c78f585ffe968b632c5ae0499

Seems this image `cesanta/docker_auth` supports hash password. Could you please show me the usage on how to change from plain text to encrypt password in password.txt?

Should I replace the hash directly? Will it work?

```
/usr/sbin/slappasswd -h {SSHA}
```

**Comment by kwk** [comment]
@SydOps For LDAP check the reference.yaml in the docker_auth project: https://github.com/cesanta/docker_auth/blob/master/examples/reference.yml#L103
There you can specify a password file.
For MongoDB password you can check this line: https://github.com/cesanta/docker_auth/blob/master/examples/reference.yml#L213
