### ISSUE TITLE
Test the auth server via curl

### ISSUE THREAD

**Issue by ozbillwang** [kwk/docker-registry-setup#6]
Currently I got docker_auth server running properly with docker-registry v2 and openldap. I can login and set limitation to pull/push for different openldap users. 

I'd like to set automation kitchen test which need test the auth server via curl access. 

I follow [Test the auth server](https://github.com/kwk/docker-registry-setup#test-that-ldap-auth-is-working) , but can't make it work

It always reports `auth failed`. Then check the log, I found the key generated via command `echo "USERNAME:PASSWORD" | base64` is different as the key i see in log

```
curl -H "Authorization: Basic $(echo "USERNAME:PASSWORD" | base64)" -vk "https://127.0.0.1:5001/auth?service=Docker%20registry&scope=registry:catalog:*"
```

If I replace the key which I got from log as below, I got token successfully.

```
curl -H "Authorization: Basic <KEY_IN_DOCKER_AUTH_LOG>" -vk "https://127.0.0.1:5001/auth?service=Docker%20registry&scope=registry:catalog:*"
```

Any hints for me to fix the curl command?

**Comment by lukeislucas** [comment]
It looks like it is:

`$(echo "USERNAME:PASSWORD" | base64)` minus the last four characters when I checked the output vs. the auth log
